--- #This playbook installs IIM v1.8.2 and IHS v8.5.5.0
- hosts: {{ play_host }}
  gather_facts: no
  become: yes
  become_user: '{{ svc_user }}'
  become_method: su
  vars:
    svc_user: svctnaix
    IHS_loc: /opt/IBM/HTTPServer
    PLG_loc: /opt/IBM/Plugins
    repo_loc: /app/WAS_files
    IIM_loc: /opt/IBM/InstallationManager
    imcl_loc: "{{ IIM_loc }}/eclipse/tools"
    package_name: WASSUPPL855
    package_dir: "{{ repo_loc }}/{{ package_name }}"
    package_arc: "{{ package_name }}.tar"
  tasks:
  - name: Check if the package dir exists
    stat:
      path: '{{ package_dir }}'
    register: package_stat
  - name: Expand package archive
    unarchive:
      src: "{{ repo_loc }}/{{ package_arc }}"
      dest: '{{ repo_loc }}'
    when: package_stat.stat.exists == False
  - name: Check if the repository files exists in package directory
    stat:
      path: "{{ package_dir }}/repository.config"
    register: repository_file
  - name: Check if there is a IHS installation already
    stat:
      path: "{{ IHS_loc }}/bin/apachectl"
    register: existing_ihs
  - name: Check if Plugin is already installed
    stat:
      path: "{{ PLG_loc }}/bin/versionInfo.sh"
    register: existing_plg
  - name: Install IHS package
    shell: "{{ imcl_loc }}/imcl install com.ibm.websphere.IHS.v85_8.5.5000.20130514_1044 -repositories {{ package_dir }} -installationDirectory {{ IHS_loc }} -properties 'user.ihs.httpPort=80,user.ihs.allowNonRootSilentInstall=true' -acceptLicense"
    when:
      - repository_file.stat.exists
      - existing_ihs.stat.exists == False
    register: imcl_ihs_output
  - debug:
      var: imcl_ihs_output.stdout_lines
  - name: Install PLG package
    shell: "{{ imcl_loc }}/imcl install com.ibm.websphere.PLG.v85_8.5.5000.20130514_1044 -repositories {{ package_dir }} -installationDirectory {{ PLG_loc }} -acceptLicense"
    when: existing_plg.stat.exists == False
    register: imcl_plg_output
  - debug:
      var: imcl_plg_output.stdout_lines
